#!/bin/bash

echo "🏍️ EMERGENCY MOTOCROSS FIX - CLEAN SETUP"
echo "========================================"
echo ""
echo "You have multiple conflicting scripts running! Here's how to fix it:"
echo ""
echo "🚨 STEP 1: DISABLE CONFLICTING SCRIPTS"
echo "   1. In Roblox Studio, go to ServerScriptService"
echo "   2. Add DisableOldScripts.server.lua and run it once"
echo "   3. This will disable all conflicting scripts"
echo ""
echo "🚨 STEP 2: ADD CLEAN PROTOTYPE (ONLY THESE TWO FILES)"
echo "   1. Copy CleanPrototype.server.lua → ServerScriptService"
echo "   2. Copy CleanPrototype.client.lua → StarterPlayerScripts"
echo "   3. Make sure NO OTHER scripts are enabled"
echo ""
echo "🚨 STEP 3: TEST"
echo "   1. Press Play in Studio"
echo "   2. Press R to spawn bike"
echo "   3. Use WASD to drive"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo "   • If you see multiple 'Client Starting' messages, you have duplicate client scripts"
echo "   • If bike doesn't spawn, check Output for 'CLEAN MOTOCROSS PROTOTYPE STARTING'"
echo "   • Make sure ONLY CleanPrototype scripts are running"
echo ""
echo "📋 What the clean prototype does:"
echo "   ✅ Creates working bike with physics"
echo "   ✅ Responsive WASD controls"
echo "   ✅ Automatic player seating"
echo "   ✅ Simple race track"
echo "   ✅ No conflicts with other scripts"
echo ""
echo "🎮 Once this works, we can add more features!"
echo ""
