#!/bin/bash

# generate-roblox-setup.sh - Generate copy-paste instructions for Roblox Studio

echo "🏍️ ROBLOX STUDIO SETUP INSTRUCTIONS"
echo "===================================="
echo ""
echo "📋 STEP-BY-STEP GUIDE:"
echo ""
echo "1️⃣ SERVER SCRIPTS (ServerScriptService):"
echo "   a) Create Script named 'Main'"
echo "   b) Copy this code into Main:"
echo ""
echo "--- COPY FROM HERE (Main Server Script) ---"
cat src/server/Main.server.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "   c) Create Folder named 'server' in ServerScriptService"
echo "   d) Create ModuleScript named 'GameManager' in server folder:"
echo ""
echo "--- COPY FROM HERE (GameManager) ---"
cat src/server/GameManager.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "   e) Create ModuleScript named 'DirtBike' in server folder:"
echo ""
echo "--- COPY FROM HERE (DirtBike) ---"
cat src/server/DirtBike.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "   f) Create ModuleScript named 'RaceTrack' in server folder:"
echo ""
echo "--- COPY FROM HERE (RaceTrack) ---"
cat src/server/RaceTrack.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "2️⃣ CLIENT SCRIPTS (StarterPlayer > StarterPlayerScripts):"
echo "   a) Create LocalScript named 'Main'"
echo ""
echo "--- COPY FROM HERE (Main Client Script) ---"
cat src/client/Main.client.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "   b) Create Folder named 'client' in StarterPlayerScripts"
echo "   c) Create ModuleScript named 'InputController' in client folder:"
echo ""
echo "--- COPY FROM HERE (InputController) ---"
cat src/client/InputController.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "   d) Create ModuleScript named 'UIManager' in client folder:"
echo ""
echo "--- COPY FROM HERE (UIManager) ---"
cat src/client/UIManager.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "3️⃣ SHARED SCRIPTS (ReplicatedStorage):"
echo "   a) Create Folder named 'shared' in ReplicatedStorage"
echo "   b) Create ModuleScript named 'GameConfig' in shared folder:"
echo ""
echo "--- COPY FROM HERE (GameConfig) ---"
cat src/shared/GameConfig.lua
echo ""
echo "--- END COPY ---"
echo ""
echo "🎮 TESTING:"
echo "   1. Click Play in Roblox Studio"
echo "   2. Press R to spawn your bike"
echo "   3. Use WASD to control"
echo "   4. Use 'Start Server' for multiplayer testing"
echo ""
echo "✅ Setup complete! Enjoy racing! 🏁"
